# Generated by Django 3.0.1 on 2019-12-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JapanBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField()),
                ('rank', models.IntegerField()),
                ('sale', models.IntegerField()),
                ('sale_inc', models.IntegerField()),
                ('seat', models.IntegerField()),
                ('seat_used', models.FloatField()),
                ('rate_last_week', models.FloatField()),
                ('rate_95', models.FloatField()),
                ('estimation', models.IntegerField()),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='JapanBoxFull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_info', models.TextField()),
                ('update_time', models.DateTimeField()),
                ('store_time', models.DateField()),
            ],
        ),
    ]
