# Generated by Django 3.0.1 on 2020-01-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maoyan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField()),
                ('avgSeatView', models.FloatField()),
                ('avgShowView', models.IntegerField()),
                ('avgViewBox', models.FloatField()),
                ('boxInfo', models.FloatField()),
                ('boxRate', models.FloatField()),
                ('movieId', models.IntegerField()),
                ('movieName', models.CharField(max_length=255)),
                ('seatRate', models.FloatField()),
                ('showInfo', models.IntegerField()),
                ('showRate', models.FloatField()),
                ('sumBoxInfo', models.CharField(max_length=31)),
                ('viewInfo', models.FloatField()),
                ('viewInfoV2', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='MaoyanFull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField()),
                ('full_info', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='japanboxfull',
            name='store_time',
            field=models.DateTimeField(),
        ),
    ]
