# Generated by Django 3.0.1 on 2020-01-17 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0002_auto_20200101_1015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JapanBox',
        ),
        migrations.DeleteModel(
            name='Maoyan',
        ),
    ]
