# Generated by Django 3.0.1 on 2020-01-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0003_auto_20200117_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxOfficeMojoDomestic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=127)),
                ('day', models.IntegerField()),
                ('daily', models.IntegerField()),
                ('DOW', models.IntegerField()),
                ('date', models.DateField()),
                ('to_date', models.IntegerField()),
            ],
        ),
    ]
